import Login from 'pages/Login'
import MainLayout from 'layouts/MainLayout'

const routes = [
  {
    path: '/login',
    component: Login
  },
  {
    path: '/',
    component: MainLayout,
    children: [
      { path: '', component: () => import('pages/Index.vue') },
      { path: '/dashboard', component: () => import('pages/Dashboard.vue') },
      { path: '/actions', component: () => import('pages/Actions.vue') },
      { path: 'shopping-cart', component: () => import('pages/ShoppingCart.vue') },
      { path: 'profile', component: () => import('pages/users/Profile.vue') },
      { path: 'categories', component: () => import('pages/categories/Index.vue') },
      { path: 'categories/new', component: () => import('pages/categories/New.vue') },
      { path: 'categories/:id', component: () => import('pages/categories/Edit.vue') },
      { path: 'carriers', component: () => import('pages/carriers/Index.vue') },
      { path: 'carriers/new', component: () => import('pages/carriers/New.vue') },
      { path: 'carriers/:id', component: () => import('pages/carriers/Edit.vue') },
      { path: 'channels', component: () => import('pages/channels/Index.vue') },
      { path: 'channels/new', component: () => import('pages/channels/New.vue') },
      { path: 'channels/:id', component: () => import('pages/channels/Edit.vue') },
      { path: 'storage-types', component: () => import('pages/storageTypes/Index.vue') },
      { path: 'storage-types/new', component: () => import('pages/storageTypes/New.vue') },
      { path: 'storage-types/:id', component: () => import('pages/storageTypes/Edit.vue') },
      { path: 'storages', component: () => import('pages/storages/Index.vue') },
      { path: 'storages/new', component: () => import('pages/storages/New.vue') },
      { path: 'storages/:id', component: () => import('pages/storages/Edit.vue') },
      { path: 'lines', component: () => import('pages/lines/Index.vue') },
      { path: 'lines/new', component: () => import('pages/lines/New.vue') },
      { path: 'lines/:id', component: () => import('pages/lines/Edit.vue') },
      { path: 'marks', component: () => import('pages/mark/Index.vue') },
      { path: 'marks/new', component: () => import('pages/mark/New.vue') },
      { path: 'marks/:id', component: () => import('pages/mark/Edit.vue') },
      { path: 'units', component: () => import('pages/units/Index.vue') },
      { path: 'units/new', component: () => import('pages/units/New.vue') },
      { path: 'units/:id', component: () => import('pages/units/Edit.vue') },
      { path: 'products', component: () => import('pages/products/Index.vue') },
      { path: 'products/new', component: () => import('pages/products/New.vue') },
      { path: 'products/:id', component: () => import('pages/products/Edit.vue') },
      { path: 'prices-list', component: () => import('pages/products/PricesList.vue') },
      { path: 'suppliers', component: () => import('pages/suppliers/Index.vue') },
      { path: 'suppliers/new', component: () => import('pages/suppliers/New.vue') },
      { path: 'suppliers/:id', component: () => import('pages/suppliers/Edit.vue') },
      { path: 'drivers', component: () => import('pages/drivers/Index.vue') },
      { path: 'drivers/new', component: () => import('pages/drivers/New.vue') },
      { path: 'drivers/:id', component: () => import('pages/drivers/Edit.vue') },
      { path: 'operators', component: () => import('pages/operators/Index.vue') },
      { path: 'operators/new', component: () => import('pages/operators/New.vue') },
      { path: 'operators/:id', component: () => import('pages/operators/Edit.vue') },
      { path: 'purchase-orders', component: () => import('pages/purchaseOrders/Index.vue') },
      { path: 'orders', component: () => import('pages/purchaseOrders/IndexOrders.vue') },
      { path: 'purchase-orders/new', component: () => import('pages/purchaseOrders/New.vue') },
      { path: 'purchase-orders/:id', component: () => import('pages/purchaseOrders/Edit.vue') },
      { path: 'shipments/purcharse-order/:id/:type', component: () => import('pages/shipments/New.vue') },
      { path: 'shipments/:id/:type', component: () => import('pages/shipments/Edit.vue') },
      { path: 'shipments/:id/detail/:detailId', component: () => import('pages/shipments/Edit.vue') },
      { path: 'analyzed-shipments', component: () => import('pages/analyzedShipments/Index.vue') },
      { path: 'raw-material-shipments', component: () => import('pages/rawMaterialShipments/Index.vue') },
      { path: 'raw-material-shipments/new', component: () => import('pages/rawMaterialShipments/New.vue') },
      { path: 'raw-material-shipments/:id', component: () => import('pages/rawMaterialShipments/Edit.vue') },
      { path: 'kardex', component: () => import('pages/kardex/Index.vue') },
      { path: 'storage-inventory', component: () => import('pages/storageInventory/Index.vue') },
      { path: 'stock-minimal', component: () => import('pages/storageInventory/StockMinimal.vue') },
      { path: 'operator-report', component: () => import('pages/operatorReport/Index.vue') },
      { path: 'bags-tracking', component: () => import('pages/bagsTracking/Index.vue') },
      { path: 'bales-tracking', component: () => import('pages/balesTracking/Index.vue') },
      { path: 'production-orders', component: () => import('pages/productionOrders/Index.vue') },
      { path: 'production-orders/new', component: () => import('pages/productionOrders/New.vue') },
      { path: 'production-orders/:id', component: () => import('pages/productionOrders/Edit.vue') },
      { path: 'lots/:id', component: () => import('pages/productionLots/Edit.vue') },
      // { path: 'lots/production-order/new', component: () => import('pages/productionLots/New.vue') },
      { path: 'production-processes', component: () => import('pages/productionProcesses/Index.vue') },
      { path: 'production-processes/new', component: () => import('pages/productionProcesses/New.vue') },
      { path: 'production-processes/:id', component: () => import('pages/productionProcesses/Edit.vue') },
      { path: 'branch-offices', component: () => import('pages/branchOffices/Index.vue') },
      { path: 'branch-offices/new', component: () => import('pages/branchOffices/New.vue') },
      { path: 'branch-offices/:id', component: () => import('pages/branchOffices/Edit.vue') },
      { path: 'branch-transfers', component: () => import('pages/branchTransfers/Index.vue') },
      { path: 'branch-transfers/new', component: () => import('pages/branchTransfers/New.vue') },
      { path: 'branch-transfers/:id', component: () => import('pages/branchTransfers/Edit.vue') },
      { path: 'users', component: () => import('pages/users/Index.vue') },
      { path: 'users/new', component: () => import('pages/users/New.vue') },
      { path: 'users/:id', component: () => import('pages/users/Edit.vue') },
      { path: 'customers', component: () => import('pages/customers/Index.vue') },
      { path: 'customers/new', component: () => import('pages/customers/New.vue') },
      { path: 'customers/:id', component: () => import('pages/customers/Edit.vue') },
      { path: 'payments', component: () => import('pages/payments/Index.vue') },
      { path: 'forecast', component: () => import('pages/forecast/Index.vue') },
      { path: 'storage-exits', component: () => import('pages/storageExits/Index.vue') },
      { path: 'storage-exits/new', component: () => import('pages/storageExits/New.vue') },
      { path: 'storage-exits/:id', component: () => import('pages/storageExits/Edit.vue') },
      { path: 'bale-opening', component: () => import('pages/baleOpening/Index.vue') },
      { path: 'bale-opening/new', component: () => import('pages/baleOpening/New.vue') },
      { path: 'bale-opening/:id', component: () => import('pages/baleOpening/Edit.vue') },
      { path: 'laminates', component: () => import('pages/laminates/Index.vue') },
      { path: 'laminates/new', component: () => import('pages/laminates/New.vue') },
      { path: 'laminates/:id', component: () => import('pages/laminates/Edit.vue') },
      // { path: 'forecast', component: () => import('pages/forecast/Index.vue') },
      { path: 'requested-orders', component: () => import('pages/requestedOrders/Index.vue') },
      { path: 'requested-orders/:id', component: () => import('pages/requestedOrders/Edit.vue') },
      { path: 'approved-orders', component: () => import('pages/approvedOrders/Index.vue') },
      { path: 'approved-orders/:id', component: () => import('pages/approvedOrders/Edit.vue') },
      { path: 'orders-to-be-produced', component: () => import('pages/ordersToBeProduced/Index.vue') },
      { path: 'sales-report', component: () => import('pages/reports/Sales.vue') },
      { path: 'shopping-carts', component: () => import('pages/shoppingCarts/Index.vue') },
      { path: 'shopping-carts-reports', component: () => import('pages/shoppingCarts/Reports.vue') },
      { path: 'shopping-carts/new', component: () => import('pages/shoppingCarts/New.vue') },
      { path: 'shopping-carts/orders/:id', component: () => import('pages/shoppingCarts/Orders.vue') },
      { path: 'shopping-carts/:id', component: () => import('pages/shoppingCarts/Edit.vue') },
      { path: 'shopping-carts-sales-point', component: () => import('pages/shoppingCartsSalesPoint/Index.vue') },
      { path: 'shopping-carts-sales-point/new', component: () => import('pages/shoppingCartsSalesPoint/New.vue') },
      { path: 'shopping-carts-sales-point/orders/:id', component: () => import('pages/shoppingCartsSalesPoint/Orders.vue') },
      { path: 'shopping-carts-sales-point/:id', component: () => import('pages/shoppingCartsSalesPoint/Edit.vue') },
      { path: 'reports/vd', component: () => import('pages/reports/Ventadetalle.vue') },
      { path: 'reports/shipments', component: () => import('pages/reports/Shipments.vue') },
      { path: 'reports/purchases', component: () => import('pages/reports/UltimasCompras.vue') },
      { path: 'reports/shopping', component: () => import('pages/reports/Shopping.vue') },
      { path: 'reports/shoppingsuppliers', component: () => import('pages/reports/ShoppingSupplier.vue') },
      { path: 'auxiliary-accountant', component: () => import('pages/reports/AuxiliaryAccountant.vue') },
      { path: 'movements', component: () => import('pages/movements/Index.vue') },
      { path: 'movements/new/:id', component: () => import('pages/movements/New.vue') },
      { path: 'movements/:id', component: () => import('pages/movements/Edit.vue') },
      { path: 'currencies', component: () => import('pages/currencyTypes/Index.vue') },
      { path: 'currencies/new', component: () => import('pages/currencyTypes/New.vue') },
      { path: 'currencies/:id', component: () => import('pages/currencyTypes/Edit.vue') },
      { path: 'exchanges', component: () => import('pages/exchangeTypes/Index.vue') },
      { path: 'exchanges/new', component: () => import('pages/exchangeTypes/New.vue') },
      { path: 'exchanges/:id', component: () => import('pages/exchangeTypes/Edit.vue') },
      { path: 'movements/newTransfer/:id', component: () => import('pages/movements/Transfer.vue') },
      { path: 'departments', component: () => import('pages/resourcesDepartments/Index.vue') },
      { path: 'departments/new', component: () => import('pages/resourcesDepartments/New.vue') },
      { path: 'departments/:id', component: () => import('pages/resourcesDepartments/Edit.vue') },
      { path: 'areas', component: () => import('pages/resourcesAreas/Index.vue') },
      { path: 'areas/new', component: () => import('pages/resourcesAreas/New.vue') },
      { path: 'areas/:id', component: () => import('pages/resourcesAreas/Edit.vue') },
      { path: 'positions', component: () => import('pages/resourcesPositions/Index.vue') },
      { path: 'positions/new', component: () => import('pages/resourcesPositions/New.vue') },
      { path: 'positions/:id', component: () => import('pages/resourcesPositions/Edit.vue') },
      { path: 'shifts', component: () => import('pages/resourcesShifts/Index.vue') },
      { path: 'shifts/new', component: () => import('pages/resourcesShifts/New.vue') },
      { path: 'shifts/:id', component: () => import('pages/resourcesShifts/Edit.vue') },
      { path: 'timetables', component: () => import('pages/resourcesTimetables/Index.vue') },
      { path: 'timetables/new', component: () => import('pages/resourcesTimetables/New.vue') },
      { path: 'timetables/:id', component: () => import('pages/resourcesTimetables/Edit.vue') },
      { path: 'employees', component: () => import('pages/resourcesEmployees/Index.vue') },
      { path: 'employees/new', component: () => import('pages/resourcesEmployees/New.vue') },
      { path: 'employees/:id', component: () => import('pages/resourcesEmployees/Edit.vue') },
      { path: 'works', component: () => import('pages/handiwork/Index.vue') },
      { path: 'works/new', component: () => import('pages/handiwork/New.vue') },
      { path: 'works/:id', component: () => import('pages/handiwork/Edit.vue') },
      { path: 'holidays', component: () => import('pages/resourcesHolidays/Index.vue') },
      { path: 'holidays/new', component: () => import('pages/resourcesHolidays/New.vue') },
      { path: 'holidays/:id', component: () => import('pages/resourcesHolidays/Edit.vue') },
      { path: 'vacation-grants', component: () => import('pages/resourcesVacations/Index.vue') },
      { path: 'vacation-grants/new', component: () => import('pages/resourcesVacations/New.vue') },
      { path: 'vacation-grants/:id', component: () => import('pages/resourcesVacations/Edit.vue') },
      { path: 'incidencia_type', component: () => import('pages/resourcesIncidences/Index.vue') },
      { path: 'incidencia_type/new', component: () => import('pages/resourcesIncidences/New.vue') },
      { path: 'incidencia_type/:id', component: () => import('pages/resourcesIncidences/Edit.vue') },
      { path: 'vacation-request', component: () => import('pages/resourcesVacations/Request.vue') },
      { path: 'ranges', component: () => import('pages/ranges/Index.vue') },
      { path: 'ranges/new', component: () => import('pages/ranges/New.vue') },
      { path: 'ranges/:id', component: () => import('pages/ranges/Edit.vue') },
      { path: 'expenses', component: () => import('pages/expenses/Index.vue') },
      { path: 'expenses/new', component: () => import('pages/expenses/New.vue') },
      { path: 'expenses/:id', component: () => import('pages/expenses/Edit.vue') },
      { path: 'trips', component: () => import('pages/trips/Index.vue') },
      { path: 'trips/new', component: () => import('pages/trips/New.vue') },
      { path: 'trips/:id', component: () => import('pages/trips/Edit.vue') },
      { path: 'vehicle-types', component: () => import('pages/vehicleTypes/Index.vue') },
      { path: 'vehicle-types/new', component: () => import('pages/vehicleTypes/New.vue') },
      { path: 'vehicle-types/:id', component: () => import('pages/vehicleTypes/Edit.vue') },
      { path: 'vehicle', component: () => import('pages/vehicle/Index.vue') },
      { path: 'vehicle/new', component: () => import('pages/vehicle/New.vue') },
      { path: 'vehicle/:id', component: () => import('pages/vehicle/Edit.vue') },
      { path: 'state', component: () => import('pages/state/Index.vue') },
      { path: 'state/new', component: () => import('pages/state/New.vue') },
      { path: 'state/:id', component: () => import('pages/state/Edit.vue') },
      { path: 'municipality', component: () => import('pages/municipality/Index.vue') },
      { path: 'municipality/new', component: () => import('pages/municipality/New.vue') },
      { path: 'municipality/:id', component: () => import('pages/municipality/Edit.vue') },
      { path: 'lotTrip/new/:id', component: () => import('pages/lotTrip/New.vue') },
      { path: 'lotTrip/:id', component: () => import('pages/lotTrip/Edit.vue') },
      { path: 'reports/production-incentives', component: () => import('pages/reports/ProductionIncentives.vue') },
      { path: 'files/:id', component: () => import('pages/files/Index.vue') },
      { path: 'repositories', component: () => import('pages/repositories/Index.vue') },
      { path: 'repositories/new', component: () => import('pages/repositories/New.vue') },
      { path: 'repositories/:id', component: () => import('pages/repositories/Edit.vue') },
      { path: 'accounts', component: () => import('pages/accounts/Index.vue') },
      { path: 'accounts/new', component: () => import('pages/accounts/New.vue') },
      { path: 'accounts/:id', component: () => import('pages/accounts/Edit.vue') },
      { path: 'outputs-types', component: () => import('pages/outputsTypes/Index.vue') },
      { path: 'outputs-types/new', component: () => import('pages/outputsTypes/New.vue') },
      { path: 'outputs-types/:id', component: () => import('pages/outputsTypes/Edit.vue') },
      { path: 'trade-movements', component: () => import('pages/tradeMovements/Index.vue') },
      { path: 'trade-movements/new', component: () => import('pages/tradeMovements/New.vue') },
      { path: 'trade-movements/:id', component: () => import('pages/tradeMovements/Edit.vue') },
      { path: 'roles', component: () => import('pages/roles/Index.vue') },
      { path: 'roles/new', component: () => import('pages/roles/New.vue') },
      { path: 'roles/:id', component: () => import('pages/roles/Edit.vue') },
      { path: 'close-sale', component: () => import('pages/closeSales/Index.vue') },
      { path: 'close-sale-remission', component: () => import('pages/closeSalesRemission/Index.vue') },
      { path: 'close-sale-loan', component: () => import('pages/closeSalesLoan/Index.vue') },
      { path: 'debts-to-pay', component: () => import('pages/debtsToPay/Index.vue') },
      { path: 'forecast-debst', component: () => import('pages/forecastdebts/Index.vue') },
      { path: 'old-balance', component: () => import('pages/oldBalance/Index.vue') },
      { path: 'dashboard-inventory', component: () => import('pages/dashboard/Inventario.vue') },
      { path: 'supercluster', component: () => import('pages/supercluster/Index.vue') },
      { path: 'supercluster/new', component: () => import('pages/supercluster/New.vue') },
      { path: 'supercluster/:id', component: () => import('pages/supercluster/Edit.vue') }
    ]
  }
]

// Always leave this as last one
if (process.env.MODE !== 'ssr') {
  routes.push({
    path: '*',
    component: () => import('pages/Error404.vue')
  })
}

export default routes
